export const timeline = [
  {
    id: 0,
    icon: 'feather:phone-call',
    picture: undefined,
    title: "Call Danny at Colby's",
    time: 'Today - 11:30am',
    color: 'primary',
  },
  {
    id: 1,
    icon: 'feather:phone-call',
    picture: '/demo/avatars/7.jpg',
    title: 'Meeting with Alice',
    time: 'Today - 01:00pm',
    color: '',
  },
  {
    id: 2,
    icon: 'feather:message-circle',
    picture: undefined,
    title: "Answer Annie's message",
    time: 'Today - 01:45pm',
    color: 'info',
  },
  {
    id: 3,
    icon: 'feather:mail',
    picture: undefined,
    title: 'Send new campaign',
    time: 'Today - 02:30pm',
    color: 'success',
  },
  {
    id: 4,
    icon: 'feather:smile',
    picture: undefined,
    title: 'Project review',
    time: 'Today - 03:30pm',
    color: '',
  },
  {
    id: 5,
    icon: 'feather:phone-call',
    picture: undefined,
    title: 'Call Trisha Jackson',
    time: 'Today - 05:00pm',
    color: 'orange',
  },
  {
    id: 6,
    icon: 'feather:feather',
    picture: undefined,
    title: 'Write proposal for Don',
    time: 'Today - 06:00pm',
    color: 'yellow',
  },
]
