export const users = [
  {
    id: '13',
    name: 'Tara Svenson',
    shortname: 'Tara S.',
    location: 'New York, NY',
    email: 'tara@test.com',
    role: 'UI/UX Designer',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
    },
    progress: 65,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '37',
    name: 'Helmut Fritz',
    shortname: 'Helmut F.',
    location: 'Paris, France',
    email: 'helmut@test.com',
    role: 'Product Manager',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/flags/france.svg',
    },
    progress: 38,
    invoice: 'invoice_03_06_2022',
    status: 'completed',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Google',
    drug: 'Sitramon',
    phone: '+998998764321n',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '25',
    name: 'Melany Wallace',
    shortname: 'Melany W.',
    location: 'San Jose, CA',
    email: 'melany@test.com',
    role: 'Web Developer',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/stacks/js.svg',
    },
    progress: 58,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Facebook',
    drug: 'Kupen',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '29',
    name: 'Hakeem Calami',
    shortname: 'Hakeem C.',
    location: 'Berlin, Germany',
    email: 'hakeem@test.com',
    role: 'Software Engineer',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/stacks/python.svg',
    },
    progress: 85,
    invoice: 'invoice_03_06_2022',
    status: 'completed',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Microsoft',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '39',
    name: 'Alejandro Badajoz',
    shortname: 'Alejandro B.',
    location: 'New York, NY',
    email: 'alejandro@test.com',
    role: 'Business Analyst',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
    },
    progress: 28,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Yahoo',
    drug: 'Hydrolife',
    phone: '+998998764321fe',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '40',
    name: 'Jeanne Marchand',
    shortname: 'Jeanne M.',
    location: 'Paris, France',
    email: 'jeanne@test.com',
    role: 'Mobile Developer',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/stacks/android.svg',
    },
    progress: 67,
    invoice: 'invoice_03_06_2022',
    status: 'rejected',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Yahoo',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '19',
    name: 'Greta Kroppfer',
    shortname: 'Greta K.',
    location: 'Berlin, Germany',
    email: 'greta@test.com',
    role: 'Sales Manager',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/flags/germany.svg',
    },
    progress: 56,
    invoice: 'invoice_03_06_2022',
    status: 'completed',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '9',
    name: 'Ana Baker',
    shortname: 'Ana B.',
    location: 'San Francisco, CA',
    email: 'ana@test.com',
    role: 'UI/UX Designer',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/stacks/photoshop.svg',
    },
    progress: 12,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Riddit LLC',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '5',
    name: 'Mary Lebowski',
    shortname: 'Mary L.',
    location: 'San Diego, CA',
    email: 'mary@test.com',
    role: 'Project Manager',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
    },
    progress: 29,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '32',
    name: 'Jonathan Krugger',
    shortname: 'Jonathan K.',
    location: 'Los Angeles, CA',
    email: 'jonathan@test.com',
    role: 'Product Manager',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
    },
    progress: 91,
    invoice: 'invoice_03_06_2022',
    status: 'completed',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '36',
    name: 'Benoit Leblanc',
    shortname: 'Benoit L.',
    location: 'Paris, France',
    email: 'benoit@test.com',
    role: 'Software Engineer',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/stacks/reactjs.svg',
    },
    progress: 44,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '38',
    name: 'Christie Dallas',
    shortname: 'Christie D.',
    location: 'Los Angeles, CA',
    email: 'christie@test.com',
    role: 'Web Developer',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/stacks/vuejs.svg',
    },
    progress: 61,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '26',
    name: 'Courtney Wilson',
    shortname: 'Courtney W.',
    location: 'Melbourne, Australia',
    email: 'courtney@test.com',
    role: 'Web Developer',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/stacks/html5.svg',
    },
    progress: 53,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '16',
    name: 'Jason Guarank',
    shortname: 'Jason G.',
    location: 'Houston, TX',
    email: 'jason@test.com',
    role: 'Business Analyst',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
    },
    progress: 78,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '23',
    name: 'Irina Vierbovsky',
    shortname: 'Irina V.',
    location: 'San Diego, CA',
    email: 'irina@test.com',
    role: 'Project Manager',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
    },
    progress: 36,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '28',
    name: 'Edouard Falant',
    shortname: 'Edouard F.',
    location: 'Paris, France',
    email: 'edouard@test.com',
    role: 'Web Developer',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/stacks/angular.svg',
    },
    progress: 49,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '7',
    name: 'Alice Carasca',
    shortname: 'Alice C.',
    location: 'San Diego, CA',
    email: 'alice@test.com',
    role: 'Software Engineer',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/stacks/csharp.svg',
    },
    progress: 78,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
  {
    id: '22',
    name: 'Dwayne Hicks',
    shortname: 'Dwayne H.',
    location: 'Los Angeles, CA',
    email: 'dwayne@test.com',
    role: 'Product Manager',
    bio: 'This is a nice user description that we can use as demo content.',
    medias: {
      avatar: '/images/avatars/svg/vuero-3.svg',
      badge: '/images/icons/flags/united-states-of-america.svg',
    },
    progress: 17,
    invoice: 'invoice_03_06_2022',
    status: 'pending',
    stage: 'stage_1',
    date: '2022-06-13',
    stir: 456987123,
    company: 'Amazon',
    drug: 'Analgin',
    phone: '+998998764321',
    social: [
      {
        channel: 'Linkedin',
        url: 'https://linkedin.com',
        icon: 'fab fa-linkedin-in',
      },
      {
        channel: 'Twitter',
        url: 'https://twitter.com',
        icon: 'fab fa-twitter',
      },
      {
        channel: 'Dribbble',
        url: 'https://dribbble.com',
        icon: 'fab fa-dribbble',
      },
      {
        channel: 'GitHub',
        url: 'https://github.com',
        icon: 'fab fa-github',
      },
    ],
  },
]
